---
title       : The population of the Netherlands
subtitle    : An exercise with Shiny Apps and Slidify
author      : Ed van Gasteren
job         : Data scientist to be
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

Shiny is a web application framework for R (see http://shiny.rstudio.com/). It is great and very easy to turn an analyses done with R into an interactive web application.

Slidify is a framework for making stunning presentations with very easy to use markup (see http://slidify.org/).

Both shiny and slidify are well intergrated with Rstudio (see http://www.rstudio.com/). It's a small step from your analysis in R to either presenting it (slidify) or to have others use it (shiny).

This very simple, not so stunning, presentation is done with slidify. It's about a simple web application build with shiny based on an analyses of the population of the Netherlands over time.

---

## page 3

---

## page 4

---

## page 5

Was the presentation completed in slidify or R Presenter? --> Slidify!

Was it 5 pages? --> this is the 5th slide!

Did it contain an R expression that got evaluated and displayed? --> not yet!

Was it hosted on github or Rpubs? --> github!

Was the presentation actually a presentation? (I.e. it had a legitimate pitch for the shiny application?) --> not yet

